In [1]:
from scripts.conf_file_finding import try_find_conf_file
try_find_conf_file()

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

In [2]:
import pandas as pd
import numpy as np
import datajoint as dj
import u19_pipeline.imaging_pipeline as ip
import matplotlib.pyplot as plt
import u19_pipeline.utils.tiff_utils as tu
import u19_pipeline.utils.tiff_matlab_imaging_utils as tmiu

/mnt/cup/braininit/Shared/repos/TestU19PipelinePython2/U19-pipeline-python/.venv/lib/python3.13/site-packages/datajoint/plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-05-20 18:38:31,428][INFO]: DataJoint 0.14.6 connected to alvaros@datajoint00.pni.princeton.edu:3306

In [33]:
import importlib
importlib.reload(ip)
importlib.reload(tu)
importlib.reload(tmiu)

In [34]:
behavior =  dj.create_virtual_module('behavior', 'u19_behavior')

In [35]:
imaging_key = dict()
imaging_key['recording_id'] = 679
imaging_key
original_imaging_key = imaging_key.copy()
original_imaging_key

{'recording_id': 679}

In [36]:
acquired_tiff_obj = ip.AcquiredTiff()

In [37]:
tiff_data = acquired_tiff_obj.make(imaging_key, test_mode=True)

Preparing /mnt/cup/braininit/Data/Raw/imaging/efonseca/efonseca_ef932_act131/20260508_g1/05082026

Estimating bleaching............................................................... done after 0.2 min
INSERT TIFF SPLIT:
{'recording_id': 679, 'tiff_split': 1, 'tiff_split_directory': 'efonseca/efonseca_ef932_act131/20260508_g1/05082026', 'fov_depth': 0, 'fov_center_xy': 0, 'fov_size_xy': 0, 'fov_rotation_degrees': 0, 'fov_pixel_resolution_xy': 0, 'fov_discrete_plane_mode': 0, 'power_percent': 45.0}
tiffsplit_2photon_key
{'recording_id': 679, 'tiff_split': 1, 'tiff_split_directory': 'efonseca/efonseca_ef932_act131/20260508_g1/05082026', 'fov_depth': 0, 'fov_center_xy': 0, 'fov_size_xy': 0, 'fov_rotation_degrees': 0, 'fov_pixel_resolution_xy': 0, 'fov_discrete_plane_mode': 0, 'power_percent': 45.0}

In [38]:
original_imaging_key

{'recording_id': 679}

In [39]:
acquired_tiff_entry = (ip.AcquiredTiff & original_imaging_key).fetch(as_dict=True)
tiff_split_entry =  (ip.TiffSplit & original_imaging_key).fetch(as_dict=True)
tiff_split_file_entry = (ip.TiffSplit.File & original_imaging_key).fetch(as_dict=True)

In [40]:
original_acqtiff_rec = pd.DataFrame(acquired_tiff_entry)
original_acqtiff_rec.T

                                                                           0
recording_id                                                             679
file_name_base             efonseca/efonseca_ef932_act131/20260508_g1/050...
scan_width                                                               512
scan_height                                                              300
acq_time                                                 2026-05-08 00:00:00
n_depths                                                                   0
scan_depths                                                         [[-1.0]]
frame_rate                                                           10.0454
inter_fov_lag_sec                                                      0.001
frame_ts_sec               [[0.0], [0.019913865], [0.03982773], [0.059741...
power_percent                                                           45.0
channels                                                             [[1.0]]
cfg_filename                                              'C:\mika_again.cfg
usr_filename                                                    'C:\mika.usr
fast_z_lag                                                               0.0
fast_z_flyback_time                                                      0.0
line_period                                                         0.000063
scan_frame_period                                                    0.01991
scan_volume_rate                                                     10.0454
flyback_time_per_frame                                                 0.001
flyto_time_per_scan_field                                              0.001
fov_corner_points          [[-204.75, -315.0], [204.75, -315.0], [204.75,...
nfovs                                                                      1
nframes                                                               118498
nframes_good                                                          118498
last_good_file                                                            60
motion_correction_enabled                                                  0
motion_correction_mode                                                   N/A
stacks_enabled                                                             0
stack_actuator                                                           N/A
stack_definition                                                         N/A

In [41]:
new_acqtiff_rec = pd.DataFrame([tiff_data[0]])
new_acqtiff_rec.T

                                                                           0
recording_id                                                             679
file_name_base             /efonseca/efonseca_ef932_act131/20260508_g1/05...
scan_width                                                               512
scan_height                                                              300
acq_time                                                 2026-05-08 15:21:27
n_depths                                                                   0
scan_depths                                                               -1
frame_rate                                                           10.0454
inter_fov_lag_sec                                                      0.001
frame_ts_sec               [0.0, 0.019913865, 0.03982773, 0.05974156, 0.0...
power_percent                                                           45.0
channels                                                                   1
cfg_filename                                              'C:\mika_again.cfg
usr_filename                                                    'C:\mika.usr
fast_z_lag                                                               0.0
fast_z_flyback_time                                                        0
line_period                                                         0.000063
scan_frame_period                                                    0.01991
scan_volume_rate                                                     10.0454
flyback_time_per_frame                                                 0.001
flyto_time_per_scan_field                                              0.001
fov_corner_points          [[-204.75, -315.0], [204.75, -315.0], [204.75,...
nfovs                                                                      1
nframes                                                               118498
nframes_good                                                          118498
last_good_file                                                            60

In [42]:
new_tiffsplit_rec = pd.DataFrame([tiff_data[1]])
new_tiffsplit_rec.T

                                                                         0
recording_id                                                           679
tiff_split                                                               1
tiff_split_directory     efonseca/efonseca_ef932_act131/20260508_g1/050...
fov_depth                                                                0
fov_center_xy                                                            0
fov_size_xy                                                              0
fov_rotation_degrees                                                     0
fov_pixel_resolution_xy                                                  0
fov_discrete_plane_mode                                                  0
power_percent                                                         45.0

In [43]:
pd.DataFrame(tiff_split_entry).T

                                                                         0
recording_id                                                           679
tiff_split                                                               1
tiff_split_directory     efonseca/efonseca_ef932_act131/20260508_g1/050...
tiff_split_name                                                       None
fov_depth                                                              0.0
fov_center_xy                                                      [[0.0]]
fov_size_xy                                                        [[0.0]]
fov_rotation_degrees                                                   0.0
fov_pixel_resolution_xy                                            [[0.0]]
fov_discrete_plane_mode                                                  0
power_percent                                                         45.0